<div class="page-title">
    <h1><?php echo $this->__('Bạn đã quên mật khẩu?') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<ul class="messages">
	<li class="success-msg">
		<ul>
			<li style="text-align: justify;">
				<span>
					<?php echo $this->__('Nếu có tài khoản đăng ký với email <strong>%s</strong>, bạn sẽ nhận được email để thiết lập lại mật khẩu.', $this->getRequest()->getParam('m')) ?>
					<p><?php echo $this->__('Vui lòng kiểm tra email của bạn.') ?></p>
				</span>
			</li>
		</ul>
	</li>
</ul>