<?php $data = $this->getFormData(); ?>
<div class="create-cv">
    <div class="page-title">
        <h1><?php echo $this->__('Tạo hồ sơ') ?></h1>
    </div>
    <form action="/<?php echo Mage::helper('job')->getCreateCVUrl() ?>" method="post" id="form-validate">
    	<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
    	<div class="row heading">
    		<span><?php echo $this->__('Thông tin chung') ?></span>
    	</div>
    	<div class="row row2">
    		<input readonly required type="text" class="first" id="ho" name="ho" placeholder="<?php echo $this->__('Họ') ?>" value="<?php echo $this->getCustomer()->getLastname() ?>" />
    		<input readonly required type="text" class="last" id="ten" name="ten" placeholder="<?php echo $this->__('Tên') ?>" value="<?php echo $this->getCustomer()->getFirstname() ?>" />
    	</div>
    	
    	<div class="row row3">
    		<span class="re">*</span>
    		<span class="re re3">*</span>
    		<select required id="day" class="first" name="day">
    			<option value=""><?php echo $this->__('Ngày') ?></option>
            	<?php 
            	for($i = 1; $i <= 31;$i++): ?>
            	<option <?php echo ($data['day']==$i) ? 'selected="selected"' : '' ?> value="<?php echo $i ?>"><?php echo $i ?></option>
            	<?php endfor; ?>
    		</select>
    		<select required id="month" name="month" class="middle">
    			<option value=""><?php echo $this->__('Tháng') ?></option>
            	<?php 
            	for($i = 1; $i <= 12;$i++): ?>
            	<option <?php echo ($data['month']==$i) ? 'selected="selected"' : '' ?> value="<?php echo $i ?>"><?php echo $this->__('Tháng') .' '. $i ?></option>
            	<?php endfor; ?>
    		</select>
    		<input readonly class="last select" id="year" type="text" name="year" value="<?php echo $this->getCustomer()->getBirthYear() ?>" />
    	</div>
    	
    	<div class="row row2 clearfix">
    		<input readonly type="text" id="sex" class="first select" name="sex" value="<?php echo $this->getCustomer()->getSex() ?>" />
    		<select name="nation" id="nation" class="last">
    			<option value=""><?php echo $this->__('Quốc tịch') ?></option>
    			<option value="<?php echo $this->__('Indonesia') ?>"><?php echo $this->__('Indonesia') ?></option>
    			<option value="<?php echo $this->__('Vietnam') ?>"><?php echo $this->__('Vietnam') ?></option>
    			<option value="<?php echo $this->__('Nước ngoài') ?>"><?php echo $this->__('Nước ngoài') ?></option>
    		</select>
    	</div>
    	
    	<div class="row row1">
    		<input type="text" name="address" id="address" placeholder="<?php echo $this->__('Địa chỉ cư trú') ?>" />
    	</div>
    	
    	<div class="row row2">
    		<input readonly class="first select" type="text" id="location" name="location" value="<?php echo Mage::getModel('job/location')->load($this->getCustomer()->getLocation())->getName() ?>" />
    		
    		<select name="country" id="country" class="last">
    			<option value=""><?php echo $this->__('Quốc gia') ?></option>
    			<option value="<?php echo $this->__('Indonesia') ?>"><?php echo $this->__('Indonesia') ?></option>
    			<option value="<?php echo $this->__('Vietnam') ?>"><?php echo $this->__('Vietnam') ?></option>
    			<option value="<?php echo $this->__('Malaysia') ?>"><?php echo $this->__('Malaysia') ?></option>
    			<option value="<?php echo $this->__('Nhật Bản') ?>"><?php echo $this->__('Nhật Bản') ?></option>
    		</select>
    	</div>
    	
    	<div class="row row2">
    		<span class="re">*</span>
    		<input required type="number" class="first" name="phone" id="phone" placeholder="<?php echo $this->__('Di động*') ?>" />
    		<input readonly required type="text" class="last" name="email" id="email" placeholder="Email*" value="<?php echo $this->getCustomer()->getEmail() ?>" />
    	</div>
    	
    	<div class="row row3">
    		<input type="number" class="first" name="salary" id="salary" placeholder="<?php echo $this->__('Mức lương hiện tại') ?>" />
    		<select class="mid" name="currency" id="currency">
    			<option value=""><?php echo $this->__('Tiền tệ') ?></option>
    			<option value="USD">USD</option>
    			<option value="IDR">IDR</option>
    			<option value="JPY">JPY</option>
    		</select>
    		<select class="last" name="salarytype" id="salarytype">
    			<option value="">Gross/NET</option>
    			<option value="Gross">Gross</option>
    			<option value="NET">NET</option>
    		</select>
    	</div>
    	
    	<div class="row heading">
    		<span><?php echo $this->__('Công việc mong muốn') ?></span>
    	</div>
    	
    	<div class="row row3">
    		<input required type="number" class="first" name="salary2" id="salary2" placeholder="<?php echo $this->__('Mức lương mong muốn') ?>*" />
    		<select required class="mid" name="currency2" id="currency2">
    			<option value=""><?php echo $this->__('Tiền tệ') ?></option>
    			<option value="USD">USD</option>
    			<option value="IDR">IDR</option>
    			<option value="JPY">JPY</option>
    		</select>
    		<select required class="last" name="salarytype2" id="salarytype2">
    			<option value="">Gross/NET</option>
    			<option value="Gross">Gross</option>
    			<option value="NET">NET</option>
    		</select>
    	</div>
    	
    	<div class="row row2">
    		<span class="re">*</span>
    		<span class="re re2">*</span>
    		<select required class="first" name="category" id="category">
    			<option value=""><?php echo $this->__('Ngành nghề') ?></option>
				<?php echo $this->getCategoryList($data['category']) ?>
    		</select>
    		<select required class="last" name="function" id="function">
    			<option value=""><?php echo $this->__('Chức năng') ?></option>
				<?php echo $this->getFunctionList($data['function']) ?>
    		</select>
    	</div>
    	
    	<div class="row row2">
    		<select class="first" name="location2" id="location2">
    			<option value=""><?php echo $this->__('Địa điểm') ?></option>
    			<?php $list = Mage::getModel('job/location')->getCollection() ?>
				<?php foreach($list as $loc): ?>
					<option <?php echo ($data['location2']==$loc->getId()) ? 'selected="selected"' : '' ?> value="<?php echo $loc->getName() ?>"><?php echo $loc->getName() ?></option>
				<?php endforeach; ?>
    		</select>
    		<select class="last" name="level" id="level">
    			<option value=""><?php echo $this->__('Cấp độ công việc') ?></option>
    			<option value="New Graduates/Entry Level"><?php echo $this->__('Mới Tốt Nghiệp/Chưa Có Kinh Nghiệm') ?></option>
    			<option value="Experienced"><?php echo $this->__('Có Kinh Nghiệm') ?></option>
    			<option value="Team Leader/Supervisor/Assistant Manager"><?php echo $this->__('Trưởng Nhóm/Giám Sát/Trợ Lý') ?></option>
    			<option value="Manager"><?php echo $this->__('Quản Lý') ?></option>
    			<option value="Executive Management"><?php echo $this->__('Quản Lý Cấp Cao') ?></option>
    		</select>
    	</div>
    	
    	<div class="row heading">
    		<span><?php echo $this->__('Trình độ học vấn') ?></span>
    		<div class="last">
	    		<input type="radio" name="education" value="1" /> <?php echo $this->__('Nước ngoài') ?>
	    		<input type="radio" name="education" value="2" /> <?php echo $this->__('Indonesia') ?>
    		</div>
    	</div>
    	
    	<div class="row row2">
    		<input type="text" class="first" name="school" placeholder="<?php echo $this->__('Tên trường') ?>" />
    		<input type="text" class="last" name="spec" placeholder="<?php echo $this->__('Chuyên ngành') ?>" />
    	</div>
    	
    	<div class="row row2">
    		<select name="degree" id="degree" class="first">
    			<option value=""><?php echo $this->__('Bằng cấp') ?></option>
    			<option value="Diploma"><?php echo $this->__('Trung cấp') ?></option>
    			<option value="College"><?php echo $this->__('Cao đẳng') ?></option>
    			<option value="Bachelor"><?php echo $this->__('Đại học') ?></option>
    			<option value="Master"><?php echo $this->__('Thạc sĩ') ?></option>
    			<option value="Doctor"><?php echo $this->__('Tiến sĩ') ?></option>
    		</select>
    		<select name="graduate" id="graduate" class="last">
    			<option value=""><?php echo $this->__('Năm tốt nghiệp') ?></option>
    			<?php 
            	$y = (int) Date('Y');
            	for($i = $y; $i >= $y-40;$i--): ?>
            	<option <?php echo ($data['graduate']==$i) ? 'selected="selected"' : '' ?> value="<?php echo $i ?>"><?php echo $i ?></option>
            	<?php endfor; ?>
    		</select>
    	</div>
    	
    	<div class="row heading">
    		<span><?php echo $this->__('Kinh nghiệm') ?></span>
    		<div class="last">
    			<input type="checkbox" name="newgraduate" id="newgraduate" value="1"/> <?php echo $this->__('Tôi vừa mới ra trường, chưa có kinh nghiệm làm việc') ?>
    		</div>
    	</div>
    	
    	<div class="row row2">
    		<span class="re">*</span>
    		<span class="re re2">*</span>
    		<select required class="first" name="category2" id="category2">
    			<option value=""><?php echo $this->__('Ngành nghề') ?></option>
				<?php echo $this->getCategoryList($data['category2']) ?>
    		</select>
    		<select required class="last" name="function2" id="function2">
    			<option value=""><?php echo $this->__('Chức năng') ?></option>
				<?php echo $this->getFunctionList($data['function2']) ?>
    		</select>
    	</div>
    	
    	<div class="row row2">
    		<select class="first" name="level2" id="level2">
    			<option value=""><?php echo $this->__('Cấp độ công việc') ?></option>
    			<option value="New Graduates/Entry Level"><?php echo $this->__('Mới Tốt Nghiệp/Chưa Có Kinh Nghiệm') ?></option>
    			<option value="Experienced"><?php echo $this->__('Có Kinh Nghiệm') ?></option>
    			<option value="Team Leader/Supervisor/Assistant Manager"><?php echo $this->__('Trưởng Nhóm/Giám Sát/Trợ Lý') ?></option>
    			<option value="Manager"><?php echo $this->__('Quản Lý') ?></option>
    			<option value="Executive Management"><?php echo $this->__('Quản Lý Cấp Cao') ?></option>
    		</select>
    		<select name="exp" id="exp" class="last">
    			<option value=""><?php echo $this->__('Số năm kinh nghiệm') ?></option>
    			<?php for($i=1;$i<41;$i++): ?>
    			<option <?php echo ($data['exp']==$i) ? 'selected="selected"' : '' ?> value="<?php echo $i ?>"><?php echo $i ?> <?php echo $this->__('tahun') ?></option>
    			<?php endfor; ?>
    		</select>
    	</div>
    	
    	<div class="row row1">
    		<textarea placeholder="<?php echo $this->__('Chi tiết công việc') ?>" name="detail" id="detail"></textarea>
    	</div>
    	
    	<div class="row heading">
    		<span><?php echo $this->__('Ngôn ngữ') ?></span>
    	</div>
    	
    	<div class="row lang">
    		<div class="text">
    			<?php echo $this->__('Tiếng Anh') ?>
    		</div>
    		<select name="en" id="en">
    			<option value=""><?php echo $this->__('Cấp độ') ?></option>
    			<option value="Native"><?php echo $this->__('Bản ngữ') ?></option>
    			<option value="Advanced"><?php echo $this->__('Cao cấp') ?></option>
    			<option value="Intermediate"><?php echo $this->__('Trung cấp') ?></option>
    			<option value="Beginner"><?php echo $this->__('Sơ cấp') ?></option>
    			<option value="No"><?php echo $this->__('Không') ?></option>
    		</select>
    	</div>
    	
    	<div class="row lang">
    		<div class="text">
    			<?php echo $this->__('Tiếng Nhật') ?>
    		</div>
    		<select name="jp" id="jp">
    			<option value=""><?php echo $this->__('Cấp độ') ?></option>
    			<option value="Native"><?php echo $this->__('Bản ngữ') ?></option>
    			<option value="Advanced"><?php echo $this->__('Cao cấp') ?></option>
    			<option value="Intermediate"><?php echo $this->__('Trung cấp') ?></option>
    			<option value="Beginner"><?php echo $this->__('Sơ cấp') ?></option>
    			<option value="No"><?php echo $this->__('Không') ?></option>
    		</select>
    	</div>
    	
    	<div class="row lang">
    		<div class="text">
    			<?php echo $this->__('Tiếng Việt') ?>
    		</div>
    		<select name="vn" id="vn">
    			<option value=""><?php echo $this->__('Cấp độ') ?></option>
    			<option value="Native"><?php echo $this->__('Bản ngữ') ?></option>
    			<option value="Advanced"><?php echo $this->__('Cao cấp') ?></option>
    			<option value="Intermediate"><?php echo $this->__('Trung cấp') ?></option>
    			<option value="Beginner"><?php echo $this->__('Sơ cấp') ?></option>
    			<option value="No"><?php echo $this->__('Không') ?></option>
    		</select>
    	</div>
    	
    	<div class="row lang">
    		<textarea placeholder="<?php echo $this->__('Thêm trình độ ngoại ngữ khác') ?>" name="otherlang" id="otherlang"></textarea>
    	</div>
    	
    	<div class="row heading">
    		<span><?php echo $this->__('Kỹ năng') ?></span>
    	</div>
    	
    	<div class="row lang">
    		<textarea name="skill" id="skill"></textarea>
    	</div>
    	
    	<div class="row">
    		<input required type="radio" name="decide" value="<?php echo $this->__('Tôi muốn tìm việc/chuyển việc ngay bây giờ') ?>" /> <?php echo $this->__('Tôi muốn tìm việc/chuyển việc ngay bây giờ') ?><br />
    		<input required type="radio" name="decide" value="<?php echo $this->__('Tôi muốn chuyển nếu có công việc/công ty tốt hơn') ?>" /> <?php echo $this->__('Tôi muốn chuyển nếu có công việc/công ty tốt hơn') ?><br />
    		<input required type="radio" name="decide" value="<?php echo $this->__('Tôi muốn chuyển việc trong tương lai (sau 1 năm)') ?>" /> <?php echo $this->__('Tôi muốn chuyển việc trong tương lai (sau 1 năm)') ?><br />
    	</div>
    	
    	<div class="row">
    		<input class="btn button-blue button" type="submit" value="<?php echo $this->__('Gửi') ?>" name="submit" />
    	</div>
    </form>
</div>
<script>
(function($){
	$(document).ready(function(){
		$('#newgraduate').on('change', function(){
			if($(this).prop('checked')==true){
				$('#category2, #function2, #level2, #exp, #detail').prop('disabled', true);
			}else{
				$('#category2, #function2, #level2, #exp, #detail').prop('disabled', false);
			}
		});
		$('input[type="number"]').on('keyup', function(){
			if(!$.isNumeric($(this).val())){
				alert('Bạn chỉ được điền số trong ô này.');
			}
		});
		//$('#category,#category2,#function,#function2').select2();
	});
})(jQuery);
</script>